package com.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendao.dao.DemoGreen;

import com.greendao.dao.DemoGreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoGreenDaoConfig;

    private final DemoGreenDao demoGreenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoGreenDaoConfig = daoConfigMap.get(DemoGreenDao.class).clone();
        demoGreenDaoConfig.initIdentityScope(type);

        demoGreenDao = new DemoGreenDao(demoGreenDaoConfig, this);

        registerDao(DemoGreen.class, demoGreenDao);
    }
    
    public void clear() {
        demoGreenDaoConfig.clearIdentityScope();
    }

    public DemoGreenDao getDemoGreenDao() {
        return demoGreenDao;
    }

}
